version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17 # the primary container, where your job's commands are run
        auth:
          username: cvegamun
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
  
  test:
    docker:
      - image: cimg/node:14.17 
        auth:
          username: cvegamun
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: npx truffle test

workflows:
  build-and-test:
    jobs:
      - build
      - test