version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17 # the primary container, where your job's commands are run
        auth:
          username: cvegamun
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: pwd
      - run: uname
      - run: yarn install
      - run: yarn build
  
  test:
    docker:
      - image: cimg/node:14.17 
        auth:
          username: cvegamun
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo 'no tests to run as of yet, but at least the code is built'

workflows:
  build-and-test:
    jobs:
      - build
      - test