version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.17 
        auth:
          username: cvegamun
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: symlink python -> python3.8
          command: sudo ln -s /bin/python3.8 /bin/python
      - run: 
          name: install node_modules
          command: yarn install 
      - run:
          name: compile smart contracts
          command: npx truffle compile 
      - run:
          name: run smart contract tests
          command: npx truffle test 

workflows:
  version: 2
  build-and-test:
    jobs:
      - test