import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ActionButton from './components/ActionButton';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">dappBay!</a>
        </h1>

        <p className={styles.description}>
          Buy and sell anything using the Ethereum blockchain.
        </p>

        <div>
          <button>sell stuff</button>
        </div>

        <div>
          <h1>Products for Sale</h1>
          <div className={styles.itemsGrid}>
            <div className={styles.item}>
              <h2>🌮</h2>
              <h3>Thing 1</h3>
              <p>0.01 eth</p>
              <ActionButton action="buy" text="buy now"/>
            </div>
            <div className={styles.item}>
              <h2>🍺</h2>
              <h3>Thing 2</h3>
              <p>0.04 eth</p>
              <ActionButton action="buy" text="buy now"/>
            </div>
            <div className={styles.item}>
              <h2>🍌</h2>
              <h3>Thing 3</h3>
              <p>0.02 eth</p>
              <ActionButton action="buy" text="buy now"/>
            </div>
          </div>
        </div>

      </main>
    </div>
  )
}

export default Home
