import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ActionButton from './components/ActionButton';
import Product from './components/product';
import React, { useState, useEffect } from 'react'

const Home: NextPage = () => {
  const [loggedIn, setLoggedIn] = useState(false);
  const [user, setUser] = useState('')
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">dappBay!</a>
        </h1>

        <p className={styles.description}>
          Buy and sell anything using the Ethereum blockchain.
        </p>

        {loggedIn ? 
          <div>
            <h2>logged in as {user}</h2> 
            <ActionButton action="sell" text="List an Item"/>
          </div>
          : 
          // <ActionButton action="login" text="Start Selling"/>
          <ActionButton action="sell" text="Start Selling"/>
        }

        <div>
        </div>

        <div>
          <h1>Products for Sale</h1>
          <div className={styles.itemsGrid}>
            <Product
              image="🍔"
              title="half eaten mcchicken"
              price={0.05}
              action={loggedIn ? "buy" : "login"}
            />
            <Product
              image="👓"
              title="gucci sunglasses"
              price={0.05}
              action={loggedIn ? "buy" : "login"}
            />
            <Product
              image="🧢"
              title="fake supreme hat"
              price={0.05}
              action={loggedIn ? "buy" : "login"}
            />
          </div>
        </div>

      </main>
    </div>
  )
}

export default Home
